### ISSUE TITLE
visualizing mixer results

### ISSUE THREAD

**Issue by gnarw** [precimed/mixer#12]
I´m using mixer_figures.py to visualize MiXeR results.

I used "python precimed/mixer_figures.py one --json <out_file>.json --out <out_file>"
for the univariate analysis results.
This runs without errors and produces an Excel file.
Using "python precimed/mixer_figures.py two --json <out_file>.json --out <out_file>"
to view the bivariate analysis results, returns an error.
See the attached file for the command and error message.
[mixer_figures error.txt](https://github.com/precimed/mixer/files/3642301/mixer_figures.error.txt)

Any ideas what the problem might be ?

**Comment by ofrei** [comment]
@gnarw Sorry about that! Please pull an update, and re-run ``make_figures.py`` on the same json file.

 The problem is that the input .json file has no data to generate qq plots (which isn't there because the ``mixer.py fit`` had no ``--qq-plots`` flag).   I've updated ``make_figures.py`` to be more flexible with respect to what data is expected to be in ``.json`` file. If there is no data for plotting, ``make_figures.py two`` will, at least, generate venn diagram and a .csv table summarizing parameters.

**Comment by ofrei** [comment]
Is this resolved?

**Comment by gnarw** [comment]
Yes, this issue is resolved.
Thanks.
