### ISSUE TITLE
ValueError: Input files have distinct value

### ISSUE THREAD

**Issue by sherryfan030** [precimed/mixer#45]
Hi there,

I successfully run codes until the visualization step.it happens an error：

python3 precimed/mixer_figures.py combine --json /home/sherry/mixer/MiXer/DIABETES/T2D_noMHC.csv.gz.fit.rep@.json --out /home/sherry/mixer/MiXer/DIABETES/visualize/T2D_noMHC.fit
Traceback (most recent call last):
  File "precimed/mixer_figures.py", line 15, in <module>
    args.func(args)
  File "/home/sherry/mixer/precimed/mixer/figures.py", line 537, in execute_combine_parser
    if len(set(values)) > 1: raise(ValueError('Input files have distinct value in "{}" field: {}'.format(key, ' '.join(set(values)))))
ValueError: Input files have distinct value in "trait1_file" field: /home/sherry/mixer/MiXer/T2D_noMHC.csv.gz MiXer/T2D_noMHC.csv.gz
————————————————————
how to solve it? Thanks!

**Comment by ofrei** [comment]
@sherryfan030 Hi
``mixer_figures.py combine`` complains because it appears to see two different trait files - ``/home/sherry/mixer/MiXer/T2D_noMHC.csv.gz`` (full path) and ``MiXer/T2D_noMHC.csv.gz`` (relative path). 
The error is just a sanity check and the code should work just fine if  you remove the line that throws an error from figures.py file, and re-run  the same command https://github.com/precimed/mixer/blob/master/precimed/mixer/figures.py#L537
Or re-run the analysis using consistent path (either full or relative) across all repeats

**Comment by sherryfan030** [comment]
Hi,oferi!
Thank you for your reply.
After that I try to use consistent path across all MiXeR file and it works.
