### ISSUE TITLE
Error on mixer_figures.py

### ISSUE THREAD

**Issue by jcabanad** [precimed/mixer#53]
Hi!

First of all thank you very much for such a nice tool!

I'm following the commands in this real example, but I didn't obtain figures, only csv files. At the end of the command in this webpage its written: "These commands may produce some warnings. Pease check if figures are generated, and if so then it's safe to ignore the warnings." 

What should I do if I don't have this figures?

https://github.com/comorment/containers/blob/main/usecases/mixer_real.md

singularity shell --home $PWD:/home $SIF/python3.sif

python /tools/mixer/precimed/mixer_figures.py combine --json ADHD.fit.rep@.json --out ADHD.fit
python /tools/mixer/precimed/mixer_figures.py combine --json ADHD.test.rep@.json  --out ADHD.test
python /tools/mixer/precimed/mixer_figures.py combine --json PLS.fit.rep@.json --out PLS.fit
python /tools/mixer/precimed/mixer_figures.py combine --json PLS.test.rep@.json  --out PLS.test
python /tools/mixer/precimed/mixer_figures.py combine --json ADHD_vs_PLS.fit.rep@.json --out ADHD_vs_PLS.fit
python /tools/mixer/precimed/mixer_figures.py combine --json ADHD_vs_PLS.test.rep@.json  --out ADHD_vs_PLS.test

python /tools/mixer/precimed/mixer_figures.py one --json ADHD.fit.json PLS.fit.json --out ADHD_and_PLS.fit --trait1 ADHD PLS --statistic mean std --ext svg
python /tools/mixer/precimed/mixer_figures.py one --json ADHD.test.json PLS.test.json --out ADHD_and_PLS.test --trait1 ADHD PLS --statistic mean std --ext svg

python /tools/mixer/precimed/mixer_figures.py two --json-fit ADHD_vs_PLS.fit.json --json-test ADHD_vs_PLS.test.json --out ADHD_vs_PLS --trait1 ADHD --trait2 PLS --statistic mean std --ext svg

This is the output for the last command:

Done.
MoTTY X11 proxy: Unsupported authorisation protocol
MoTTY X11 proxy: Unsupported authorisation protocol
Traceback (most recent call last):
  File "/tools/mixer/precimed/mixer_figures.py", line 15, in <module>
    args.func(args)
  File "/tools/mixer/precimed/mixer/figures.py", line 478, in execute_two_parser
    plt.figure(figsize=[12, 3.5])
  File "/usr/local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 687, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/usr/local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"

Thank you very much.

Best,

Judit

**Comment by nasser1el** [comment]
Hi there,

I understand that this issue was closed, but I've been running in to a similar problem the last couple weeks with MiXeR producing csv files, but being unable to produce figures from these csv files. I used a similar script for other GWAS files and MiXeR worked successfully on those, so I'm not sure what the issue is.

I've attached the job output files below. For reference, the HET GWAS file already included information for SNPs, N, Z, A1, and A2. The CCBIPMDD GWAS file included information for SNPs, N, A1, and A2 and I calculated the Z score with R using P-value data and assuming a normal distribution.
[
[CCBIPMDD_HET_real.txt](https://github.com/precimed/mixer/files/7679233/CCBIPMDD_HET_real.txt)
[CCBIPMDD_HET_figures.txt](https://github.com/precimed/mixer/files/7679237/CCBIPMDD_HET_figures.txt)
](url)
